{{/*
    -----------------------------------------------------------------------------------

    ------ DESCRIPTION ------
    Mixin to get values/keys from values or a secretKeyRef
    To use this mixin, the object you pass, needs to follow the schema defined under @schema below

    ------ SCHEMA ------
    <section>
        <key>: <value>
        <useExistingSecret>:
            name: <secretName>
            keys:
                <key>: <secretKey>

    ------ USAGE ------
    Get name of the secret:
    {{ include "common.mixins.secretRef.name" (dict
        "secretName" "<autoGeneratedName>"
        "context" .auth
        "contextRef" .auth.secretKeyRef
        "key" "<key>"
    ) }}

    Get key in the secret:
    {{ include "common.mixins.secretRef.key" (dict
        "context" .auth
        "contextRef" .auth.secretKeyRef
        "key" "<key>"
    ) }}

    -----------------------------------------------------------------------------------
*/}}
{{- define "common.mixins.secretRef.name" }}
    {{- $value := (get .contextRef.keys .key) | default "" }}
    {{- if and (.contextRef.name) ($value) }}
        {{- .contextRef.name }}
    {{- else }}
        {{- .secretName }}
    {{- end }}
{{- end }}



{{- define "common.mixins.secretRef.key" }}
    {{- $value := (get .contextRef.keys .key) | default "" }}
    {{- if and (.contextRef.name) ($value) }}
        {{- $value }}
    {{- else }}
        {{- .key }}
    {{- end }}
{{- end }}