{{/*
    -----------------------------------------------------------------------------------

    ------ DESCRIPTION ------
    Mixin to get values/keys from values or a secretKeyRef
    To use this mixin, the object you pass, needs to follow the schema defined under @schema below

    ------ SCHEMA ------
    <section>
        <key>: <value>
        <useExistingSecret>:
            name: <secretName>
            keys:
                <key>: <secretKey>

    ------ USAGE ------
    Get name of the secret:
    {{ include "common.mixins.secretRef.name" (list "<autoGeneratedName>" .auth .auth.secretKeyRef "<key>") }}

    Get key in the secret:
    {{ include "common.mixins.secretRef.key" (list .auth .auth.secretKeyRef "<key>") }}

    -----------------------------------------------------------------------------------
*/}}
{{- define "common.mixins.secretRef.name" }}
    {{- $fullname := index . 0 }}
    {{- $localValues := index . 1 }}
    {{- $secretValues := index . 2 }}
    {{- $key := index . 3 }}
    
    {{- $value := (index $secretValues.keys $key) | default "" }}
    
    {{- if and ($secretValues.name) ($value) }}
        {{- $secretValues.name }}
    {{- else }}
        {{- $fullname }}
    {{- end }}
{{- end }}



{{- define "common.mixins.secretRef.key" }}
    {{- $localValues := index . 0 }}
    {{- $secretValues := index . 1 }}
    {{- $key := index . 2 }}

    {{- $value := (index $secretValues.keys $key) | default "" }}
    
    {{- if and ($secretValues.name) ($value) }}
        {{- $value }}
    {{- else }}
        {{- $key }}
    {{- end }}
{{- end }}